### PR TITLE
Try fix SCSS imports

### PR DESCRIPTION
**Pull request by pokatomnik**

### CODE REVIEW

**Comment by Mqxx** [comment]
I tried that but it did not work 😢

**Comment by Mqxx** [comment]
Maybe I will switch back to vanilla CSS. To be honest I don't even use that much of SCSS features...

**Comment by Mqxx** [comment]
But I thougth it might be nice to have...

**Comment by pokatomnik** [comment]
I would recommend try tailwind css. And you won't need to write CSS at all.

**Comment by Mqxx** [comment]
I am sorry to say this, but imo tailwind css is the worst... it bloats your html with "useless" classes. I also use the [BEM Notation](https://getbem.com/) (which I would highly recommend to use) for defining styles and elements. That way you can swap out what ever you use for your styling and stay modular...

**Pull request closed without merging**
